app:
  name: "SC2突变评分"
  version: "1.0.0"
  description: "星际争霸2合作任务突变组合生成器"
  debug: true

server:
  host: "0.0.0.0"
  port: 8000
  reload: true

model:
  vocab_dir: "resources/model/vocab"
  weights_path: "resources/model/weights/model.pt"
  network:
    map_dim: 64
    commander_dim: 96
    mutation_dim: 96
    ai_dim: 64
    hidden_dims: [256, 128, 64]
    num_classes: 5
    dropout: 0.3
    embed_dropout: 0.2
    use_batch_norm: true 