app:
  name: "SC2突变评分"
  version: "1.0.0"
  debug: true

server:
  host: "127.0.0.1"
  port: 8000
  reload: true

model:
  network:
    map_dim: 64
    commander_dim: 96
    mutation_dim: 96
    ai_dim: 64
    hidden_dims: [256, 128, 64]
    num_classes: 5
    dropout: 0.3
    embed_dropout: 0.2
    use_batch_norm: true 