# 数据配置
data:
  raw_data_path: data/processed/sc2_mutations_duo.csv
  processed_dir: data/processed
  max_mutations: 8  # 双指挥官模式，每个指挥官最多4个突变
  val_ratio: 0.1
  batch_size: 32
  num_workers: 4
  use_weighted_sampler: true

# 模型配置
model:
  # 嵌入维度
  map_dim: 48
  commander_dim: 48
  mutation_dim: 48
  ai_dim: 48
  # MLP配置
  hidden_dims: [128, 64, 32]
  dropout: 0.5
  embed_dropout: 0.3

# 训练配置
training:
  num_epochs: 100
  lr: 5.0e-4
  weight_decay: 5.0e-4
  # 学习率调度器
  scheduler:
    factor: 0.7
    patience: 8
    min_lr: 1.0e-6
  # 设备
  device: cuda

# 实验配置
experiment:
  name: focal_loss_v2  # 使用focal loss处理类别不平衡的第二个版本
  save_dir: experiments
  seed: 42 