# 全局配置
app:
  name: "SC2 Mutations Randomizer"
  version: "0.1.0"
  debug: true

# 服务配置
server:
  host: "127.0.0.1"
  port: 8000
  reload: true

# 资源配置
resources:
  images_dir: "../SC2_Co-op_Resource/src/resources/images"
  models_dir: "../experiments"
  mappings_dir: "../SC2_Co-op_Resource/src/resources/mappings"

# 模型配置
model:
  default: "baseline"
  max_cache_size: 2  # 最多同时加载的模型数量
  prediction:
    batch_size: 32
    timeout: 5.0  # 秒

# 随机生成配置
randomizer:
  max_attempts: 1000
  tolerance: 0.5
  weights:
    rule_score: 0.7
    model_score: 0.3
  constraints:
    max_mutations: 8  # 双打模式下每个指挥官最多4个突变
    min_mutations: 2  # 最少突变数量 